# Generated by Django 2.1 on 2018-09-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('accommodation_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('house_rules', models.CharField(blank=True, max_length=1000, null=True)),
                ('booking_rules', models.CharField(blank=True, max_length=1000, null=True)),
                ('amenities', models.CharField(blank=True, max_length=1000, null=True)),
                ('base_price', models.FloatField(blank=True, max_length=1000, null=True)),
                ('num_guests', models.IntegerField(blank=True, null=True)),
                ('num_bedrooms', models.IntegerField(blank=True, null=True)),
                ('num_bathrooms', models.IntegerField(blank=True, null=True)),
                ('suburb', models.CharField(blank=True, max_length=1000, null=True)),
                ('state', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=1000, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField(help_text='Start day of the rent', verbose_name='Start day of the rent')),
                ('start_day_start_time', models.TimeField(help_text='Starting time', verbose_name='Starting time')),
                ('end_day', models.DateField(help_text='End day of the event', verbose_name='End day of the event')),
                ('end_day_end_time', models.TimeField(help_text='Final time', verbose_name='Final time')),
                ('notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='catalog.Advertisement')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accommodation_pics/')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='catalog.Advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='profile_pics/')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='catalog.User_Profile'),
        ),
        migrations.AddField(
            model_name='accommodation_review',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_reviews', to='catalog.Advertisement'),
        ),
    ]
