# Generated by Django 2.1 on 2018-08-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_auto_20180814_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_name', models.CharField(max_length=50)),
                ('base_price', models.IntegerField(default=0)),
            ],
        ),
    ]
