# Generated by Django 2.1 on 2018-08-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='accommodation_description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='booking_rules',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='house_rules',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='location_country',
            field=models.CharField(default='Australia', max_length=50),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='location_state',
            field=models.CharField(default='NSW', max_length=50),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='location_suburb',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='no_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='no_bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='no_guests',
            field=models.IntegerField(default=0),
        ),
    ]
