# Generated by Django 2.1 on 2018-08-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180820_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='no_bathrooms',
            new_name='num_bathrooms',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='no_bedrooms',
            new_name='num_bedrooms',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='no_guests',
            new_name='num_guests',
        ),
    ]
