# Generated by Django 2.1 on 2018-08-20 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180820_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='location_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='location_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='location_suburb',
            new_name='suburb',
        ),
    ]
