# Generated by Django 2.1 on 2018-08-21 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180820_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=200)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Advertisement')),
            ],
        ),
    ]
